#!/bin/bash  
#PBS -N seq_matrix_mul
#PBS -q cpu 
#PBS -j oe
#PBS -l walltime=00:15:00
#PBS -l nodes=4:ppn=32
#PBS -o results/$PBS_JOBID.output

RESULTDIR=${PBS_O_WORKDIR}/results/

mkdir -pv ${RESULTDIR}
cd $PBS_O_WORKDIR


for N in 10 20 30 40 50 60 70 80 90 100 200 300 400 500 700 800 900 1000 
do
    aprun -n 1 -N 1  run_mul ${N} 1>${RESULTDIR}/N_${N}.log 2>>results/${PBS_JOBID}.output
done

echo "finish now exit"

